[project]
name = "pyffmpeg"
version = "0.1.0"
description = "ffmpeg python library"

requires-python = ">=3.13"
dependencies = []

[project.scripts]
pyffmpeg = "pyffmpeg:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
